title: Yuliana Apaza
email: yuliana.apaza94@gmail.com
description: >-
  My personal page
baseurl: ""
show_excerpts: true
permalink: /:year/:month/:day/:title.html

plainwhite:
  name: Yuliana Apaza
  tagline: Developer. Researcher
  date_format: "%b %-d, %Y"
  sitemap: true
  social_links:
    github:  yg-apaza
    linkedIn: in/yuliana-apaza

remote_theme: thelehhman/plainwhite-jekyll

collections:
  portfolio:
    output: true
  research:
